language: python
python:
 - "2.7"
install:
 - pip install .
 - pip install -r requirements.txt
script:
 - cd unit_tests
 - env PYTHONOPATH=.. python -m unittest --verbose test_all
 - cd ../robot_tests
 - env PYTHONPATH=.. python ./fps-ouch &
 - pybot *.robot

